import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../widgets/grocery_item_tile.dart';
import '../theme.dart';
import 'package:share_plus/share_plus.dart';

class GroceryListScreen extends StatefulWidget {
  final GroceryList groceryList;

  const GroceryListScreen({
    super.key,
    required this.groceryList,
  });

  @override
  State<GroceryListScreen> createState() => _GroceryListScreenState();
}

class _GroceryListScreenState extends State<GroceryListScreen> {
  late List<GroceryCategory> _categories;
  Set<String> _expandedCategories = {};
  bool _hideCheckedItems = false;

  @override
  void initState() {
    super.initState();
    _categories = widget.groceryList.categories;
    // Expand all categories by default
    _expandedCategories = _categories.map((c) => c.name).toSet();
  }

  void _toggleCategory(String categoryName) {
    setState(() {
      if (_expandedCategories.contains(categoryName)) {
        _expandedCategories.remove(categoryName);
      } else {
        _expandedCategories.add(categoryName);
      }
    });
  }

  void _toggleShoppingMode() {
    setState(() {
      _hideCheckedItems = !_hideCheckedItems;
    });
  }

  void _shareGroceryList() {
    final buffer = StringBuffer();
    buffer.writeln('🛒 CookFlow Grocery List');
    buffer.writeln('━' * 30);
    buffer.writeln();

    for (final category in _categories) {
      buffer.writeln('📦 ${category.name}');
      for (final item in category.items) {
        if (!item.isChecked || !_hideCheckedItems) {
          final check = item.isChecked ? '✓' : '○';
          buffer.writeln('  $check ${item.quantity} ${item.name}');
        }
      }
      buffer.writeln();
    }

    buffer.writeln('Generated by CookFlow 🍳');
    Share.share(buffer.toString());
  }

  int _getUncheckedCount() {
    return _categories.fold(
      0,
      (sum, category) =>
          sum + category.items.where((item) => !item.isChecked).length,
    );
  }

  @override
  Widget build(BuildContext context) {
    final uncheckedCount = _getUncheckedCount();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Grocery List'),
        actions: [
          IconButton(
            icon: Icon(_hideCheckedItems
                ? Icons.visibility_off
                : Icons.visibility),
            onPressed: _toggleShoppingMode,
            tooltip: _hideCheckedItems ? 'Show all items' : 'Hide checked items',
          ),
          IconButton(
            icon: const Icon(Icons.share),
            onPressed: _shareGroceryList,
            tooltip: 'Share list',
          ),
        ],
      ),
      body: Column(
        children: [
          // Summary Card
          Container(
            width: double.infinity,
            margin: const EdgeInsets.all(AppTheme.spacingM),
            padding: const EdgeInsets.all(AppTheme.spacingL),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  AppTheme.primaryOrange,
                  AppTheme.primaryOrange.withOpacity(0.8),
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(AppTheme.radiusL),
              boxShadow: [
                BoxShadow(
                  color: AppTheme.primaryOrange.withOpacity(0.3),
                  blurRadius: 12,
                  offset: const Offset(0, 6),
                ),
              ],
            ),
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    _buildStat(
                      icon: Icons.shopping_basket,
                      label: 'Items Left',
                      value: '$uncheckedCount',
                    ),
                    Container(
                      width: 1,
                      height: 40,
                      color: Colors.white.withOpacity(0.3),
                    ),
                    _buildStat(
                      icon: Icons.category,
                      label: 'Categories',
                      value: '${_categories.length}',
                    ),
                    Container(
                      width: 1,
                      height: 40,
                      color: Colors.white.withOpacity(0.3),
                    ),
                    _buildStat(
                      icon: Icons.restaurant_menu,
                      label: 'Recipes',
                      value: '${widget.groceryList.recipeCount}',
                    ),
                  ],
                ),
              ],
            ),
          ),

          // Category List
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.only(
                left: AppTheme.spacingM,
                right: AppTheme.spacingM,
                bottom: AppTheme.spacingXL,
              ),
              itemCount: _categories.length,
              itemBuilder: (context, index) {
                final category = _categories[index];
                final isExpanded = _expandedCategories.contains(category.name);
                final visibleItems = _hideCheckedItems
                    ? category.items.where((item) => !item.isChecked).toList()
                    : category.items;

                if (_hideCheckedItems && visibleItems.isEmpty) {
                  return const SizedBox.shrink();
                }

                return Card(
                  margin: const EdgeInsets.only(bottom: AppTheme.spacingM),
                  child: Column(
                    children: [
                      // Category Header
                      InkWell(
                        onTap: () => _toggleCategory(category.name),
                        borderRadius: BorderRadius.circular(AppTheme.radiusL),
                        child: Padding(
                          padding: const EdgeInsets.all(AppTheme.spacingM),
                          child: Row(
                            children: [
                              Container(
                                width: 48,
                                height: 48,
                                decoration: BoxDecoration(
                                  color: AppTheme.accentGreen.withOpacity(0.1),
                                  borderRadius:
                                      BorderRadius.circular(AppTheme.radiusM),
                                ),
                                child: const Icon(
                                  Icons.shopping_bag,
                                  color: AppTheme.accentGreen,
                                ),
                              ),
                              const SizedBox(width: AppTheme.spacingM),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      category.name,
                                      style: Theme.of(context)
                                          .textTheme
                                          .titleMedium
                                          ?.copyWith(
                                            fontWeight: FontWeight.bold,
                                          ),
                                    ),
                                    Text(
                                      '${visibleItems.length} items',
                                      style: Theme.of(context)
                                          .textTheme
                                          .bodySmall
                                          ?.copyWith(
                                            color: AppTheme.textMedium,
                                          ),
                                    ),
                                  ],
                                ),
                              ),
                              Icon(
                                isExpanded
                                    ? Icons.keyboard_arrow_up
                                    : Icons.keyboard_arrow_down,
                                color: AppTheme.textMedium,
                              ),
                            ],
                          ),
                        ),
                      ),

                      // Category Items
                      if (isExpanded)
                        Column(
                          children: visibleItems
                              .map((item) => GroceryItemTile(
                                    item: item,
                                    onCheckedChanged: (checked) {
                                      setState(() {
                                        item.isChecked = checked;
                                      });
                                    },
                                  ))
                              .toList(),
                        ),
                    ],
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildStat({
    required IconData icon,
    required String label,
    required String value,
  }) {
    return Column(
      children: [
        Icon(icon, color: Colors.white, size: 28),
        const SizedBox(height: 4),
        Text(
          value,
          style: const TextStyle(
            color: Colors.white,
            fontSize: 24,
            fontWeight: FontWeight.bold,
          ),
        ),
        Text(
          label,
          style: TextStyle(
            color: Colors.white.withOpacity(0.9),
            fontSize: 12,
          ),
        ),
      ],
    );
  }
}
